export const LOREM_IPSUM_VARIANTS = [
  {
    name: 'Lorem Ipsum',
    lines: [
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus commodo urna non justo sagittis, aliquet dignissim leo bibendum. Nullam suscipit sapien vel risus dapibus, id pharetra magna rhoncus. Nam malesuada, nisi id cursus congue, elit metus volutpat elit, eget fringilla nunc nunc eget sapien. Fusce vehicula libero at sem auctor, et ornare tellus hendrerit.`,
      `Quisque cursus, nisl vel fringilla aliquet, ligula turpis facilisis est, nec commodo mi felis a orci. Integer a justo ut sapien fringilla feugiat. Mauris gravida justo at turpis tempor posuere. Fusce condimentum, lacus at scelerisque pharetra, odio ligula venenatis magna, vel facilisis lectus orci eget nunc. Aliquam erat volutpat.`,
      `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.`,
      `Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.`,
      `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.`,
      `Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`,
      `Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
    ],
  },
  {
    name: 'Hodor Ipsum',
    lines: [
      `Hodor hodor hodor hodor hodor HODOR! Hodor hodor hodor hodor hodor hodor hodor hodor HODOR hodor. Hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor. Hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor HODOR!`,
      `Hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor. Hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor HODOR hodor hodor hodor. Hodor hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor.`,
      `Hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor. HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor.`,
      `Hodor hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor. Hodor hodor hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor. Hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor HODOR!`,
      `Hodor hodor hodor hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor. Hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor. HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor.`,
      `Hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor. Hodor hodor hodor hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor. Hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor.`,
      `HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor. Hodor hodor hodor hodor HODOR hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor hodor.`,
    ],
  },
  {
    name: 'Samuel L Ipsum',
    lines: [
      `Listen the fuck up, cuz I'm only gonna say this once. Lorem ipsum fucking dolor sit amet, consectetur fucking adipiscing elit, alright? Phasellus commodo urna non fucking justo sagittis, aliquet dignissim leo bibendum. Nullam suscipit fucking sapien vel risus dapibus, id pharetra magna rhoncus. Nam malesuada, nisi id cursus congue, elit metus volutpat elit, eget fringilla nunc nunc eget fucking sapien. Fusce vehicula libero at sem auctor, et ornare fucking tellus hendrerit. Got it?`,
      `Now pay fucking attention! Quisque cursus, nisl vel fringilla aliquet, ligula turpis facilisis est, nec commodo mi felis a fucking orci. You understand? Integer a justo ut sapien fringilla fucking feugiat. Mauris gravida justo at turpis tempor posuere. Fusce condimentum, lacus at scelerisque pharetra, odio ligula venenatis magna, vel facilisis lectus orci eget nunc. Aliquam erat fucking volutpat. Don't make me repeat myself.`,
      `Here’s the fucking deal. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. You got that? Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fucking fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Capisce?`,
      `I'm not done yet! Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. You following me? Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur? Don't act like you don't know what the fuck I'm saying.`,
      `Listen here, motherfucker! At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fucking fuga. Et harum quidem rerum facilis est et expedita fucking distinctio. That's right.`,
      `Ain't no fucking around here! Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor fucking repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores fucking repellat. You dig?`,
      `Now let me break it down for you! Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla fucking pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. And that's how it's fucking done.`,
    ],
  },
  {
    name: "Fo' Lorizzle my Ipsizzle",
    lines: [
      `Yo, let me holla at ya with this Lorem Ipsum flow, cuz. Lorem ipsum dolor sit amet, consectetur adipiscing elit, fo’ shizzle. Phasellus commodo urna non justo sagittis, aliquet dignissim leo bibendizzle. Nullam suscipit sapien vel risus dapibus, id pharetra magna rhoncizzle. Nam malesuada, nisi id cursus congue, elit metus volutpat elit, eget fringilla nunc nunc eget sapien. Fusce vehicula libero at sem auctor, et ornare tellus hendrerizzle.`,
      `Now, listen up, homie. Quisque cursus, nisl vel fringilla aliquet, ligula turpis facilisis est, nec commodo mi felis a orci. Integer a justo ut sapien fringilla feugiat, ya dig? Maurizzle gravida justo at turpis tempor posuere. Fusce condimentizzle, lacus at scelerisque pharetra, odio ligula venenatis magna, vel facilisis lectus orci eget nunc. Aliquam erat volutpatizzle, bro.`,
      `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.`,
      `Fo' real, fo' real. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.`,
      `Straight up, son. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.`,
      `Ain't nothing but a G thang, baby. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`,
      `Fo' shizzle, my nizzle. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
    ],
  },
  {
    name: '[REDACTED] Ipsum',
    lines: [
      `█████ █████ ████ ███, ████████ █████████ ████. ████████ ███████ ████ ███ ████████, ██████ █████████ ███ ████████. █████ ███████ ██████ ███ █████ ██████, ██ ███████ █████ ██████. ███ ████████, ████ ██ ██████ █████, ████ █████ ████████ ████, █████ ████████ ████ ████ ████ ██████. █████ ████████ ██████ ██ ████ ██████, ██ █████ █████ ████████.`,
      `██████ ████████! ██████ ██████, ████ ██ ████████ ██████, █████ █████ █████████ ███, ███ ███████ ██ █████ █ ████. ██████ █ ████ ██ █████ ████████ ██████. █████ ██████ █████ ██ █████ ██████ ██████. █████ ████████████, █████ ██ █████████ ██████, ████ ██████ ████████ █████, ███ ███████ ██████ ████ ████ ████. ███████ █████ ██████.`,
      `████ ██ ██████████ ████ █████ ████ █████ ███ █████████ ███████████ ██████████, █████ ███ ███████, █████ █████ █████ ████ ████ ████████ ██████ ██ ████ ██████ ██████████ ██ ████ ████████ ████████ ██ █████ ████████. ████ ████ █████ ███████████ ████ ████████ ████ ████ ████████ ████ ████ ████████, ███ ████ ██████ ███ ████ ████████ ████ █████████ ██████ █████ ████████.`,
      `█████ ████ ██████! ██████ █████ ████████ ████, ███ ███████ ██████ ████ █████ ███, ██████████, ███████ ██████, ███ ███████ ████, ███ ███ █████ ████ ███████ ██ ██████ ██ ████ ████████. ██ █████ ███ ██████ ████████, ████ ███████████████ ████ ██████ ██████, ████ ██ ████ ████████ ████ ████ ████████ ██████████ ██████████. ████ █████ ███ ███ ███ █████ ████ ████ ████ ████████ ████████████?`,
      `██████ ████, ██████████████! ██ ████ ███ █████ ███ ███████████ ██ ████ █████ ████ ███ ████████ ███████████ ████████ ██ ████ ████████ ████ ██████ ██████, ████ ███ ███████ ██████████ ████████ ████ █████ ████ ████ ███████ ████████ ██████, ██ ███ ████████ ████ ███████ ██████ ███████ █████ █████ ██████ ████ ████ ███████. ██ █████ ███████ ████ █████ ███ ████████ ████.`,
      `█████ ████ ████████ ████ ████ ███ ████████! ███ ██████ ███████, ███ ██████ ██████, ███ ██████ ██████ ████ ████ ████ ███ ████ ████████ ████████, ████ ██████████, ██████ ████████. █████████ ██ ████ ██████, ████ ████ ████████████ ██████████ ████ ████ ████████ ████████████████. ██ ███████ ████████ ████ ███ █████ ████ ██████████ ████ ████ ████████ ██████, ██ ███ ████████ █████████████ ██████ █████████ ████████ ██████ ████████████ ████████. ████ ███?`,
      `█████ ███ ████ ██████ ██ ████! ███ ████ ██ ███ ████████ ████ ████ ██ ███████ ████████, ███ █████ ████ ████████ ████ ████ ████████ ███████ ██████ ██████████ ████ ████ ███ ███████ ████ ███████ ████████████ ██████ ████████████. █████ ███ ████████ ████ ██ ██████ ██████ ███████████ ████████, █████ ██████ ████ ██ █████████ ███ █████████ ██████████ █████████ ████████. ████'█ ████ ████ ██'█ █████ █████ ████'█ ████ █████.`,
    ],
  },
];
